version: "3"

services:
  loadbalancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: ./nginx1
      dockerfile: Dockerfile
  server2:
    build:
      context: ./nginx2
      dockerfile: Dockerfile