version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Hello,HI  World!"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
  scheduled:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
